favicons:
  sha256hash: ["<STR: sha256 hash favicon>"]
  murmurhash: [<INT: mmh3 hash favicon>]
  enable: True

keywords:
  title: ["<title keyword>"]
  enable: True

ips:
  ips: ["<ip>"]
  enable: False