favicons:
  sha256hash: ["<STR: sha256 hash favicon>"]
  murmurhash: [<INT: mmh3 hash favicon>]
  enable: False

keywords:
  title: ["<title keyword>"]
  enable: False

ips:
  ips: ["185.163.159.72"]
  enable: True